name: ci

on:
  - push

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: true
    steps:
      - name: Checkout recurly-java-library
        uses: actions/checkout@v2
      - name: Set Java to version 8
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 8
      - name: Run tests
        env:
          API_KEY: ${{ secrets.API_KEY }}
          SUBDOMAIN: ${{ secrets.SUBDOMAIN }}
        run: |
          mvn clean test -Ptravis -Dkillbill.payment.recurly.apiKey=$API_KEY -Dkillbill.payment.recurly.subDomain=$SUBDOMAIN
