name: Release on commit to master

on:
  push:
    branches: [master]

env:
  APPLICATION: recurly-java-library

jobs:
  release:
    name: Release and publish to GitHub Packages
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
            java-version: 8
            distribution: adopt

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Generate maven settings
        uses: s4u/maven-settings-action@v2.4.1
        with:
          servers: |
            [{
                "id": "nexus",
                "username": "${{ secrets.NEXUS_USERNAME }}",
                "password": "${{ secrets.NEXUS_PASSWORD }}"
            }]

      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Prepare release
        run:  |
          mvn --batch-mode release:prepare
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


