name: Release on commit to master

on:
  push:
    branches: [master]

env:
  APPLICATION: recurly-java-library

jobs:
  release:
    name: Release and publish Google Artefeact Registry
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
            java-version: 8
            distribution: adopt

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Setup gcloud CLI
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          version: "290.0.1"

      - name: Build and Test
        uses: qcastel/github-actions-maven-release@master
        with:
          git-release-bot-name: GitHub Actions
          git-release-bot-email: actions@github.com
          access-token: "${{ secrets.GITHUB_TOKEN }}"
